theme: jekyll-theme-cayman

# Site settings
title: Blog
SEOTitle: BY Blog
# header-img: img/post-bg-desk.jpg
email: duliangwutong@gmail.com
# description: "Every failure is leading towards success."
# keyword: "BY, BY Blog, 柏荧的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone"
url: "http://duliangwu.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
# github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository
